@startuml
left to right direction
skinparam packageStyle rectangle
skinparam usecase {
  BackgroundColor White
  BorderColor Black
}

actor "Visitor" as V
actor "Initiator (Youssef)" as I
actor "Registered User (Amal)" as R
actor "Admin" as A

package "Errachidia – Sahara Solidaire" {

  usecase "Consulter Contenu\n(Articles, Détails, Favoris)" as UC_Public
  usecase "Publier / Mettre à jour Article" as UC_Publish
  usecase "Commenter / Aimer / Partager" as UC_Comment
  usecase "Rechercher / Filtrer" as UC_Search
  usecase "Gérer et Modérer Contenu" as UC_Admin
}

' Relations simplifiées
V -- UC_Public
I -- UC_Publish
R -- UC_Public
R -- UC_Comment
R -- UC_Search
A -- UC_Publish
A -- UC_Comment
A -- UC_Admin
A -- UC_Public

' Relations logiques
UC_Comment .> UC_Public : <<include>>
UC_Search .> UC_Public : <<include>>
@enduml
